// MANAGING THE SLIDER SECTION

// MANAGING THE DROPDOWN SELECTOR

// MANAGING THE PEOPLE COUNT SELECTOR

// SUBMITTING THE FORM

// CLOSING THE SUCCESS MESSAGE

// CHECKING IF AN INPUT IS NUMERIC

// VALIDATING NAME

// VALIDATING EMAIL

// VALIDATING DATE

// VALIDATING TIME